### PR TITLE
Add Gemfile.lock to .gitignore

### PR DESCRIPTION
**Pull request by KrauseFx**
Only because it's not part of the repo, I assume you don't want it on there?

### CODE REVIEW

**Comment by JohnSundell** [comment]
Hmmm this is interesting, similar to @mattiashagstrand's PR, Danger is failing with the error message:
```
Could not set up API to Code Review site for Danger
For your GitHub repo, you need to expose: DANGER_GITHUB_API_TOKEN
```
But the API token has been added, and it works for my own PRs 🤔
screen shot 2018-01-08 at 21 03 39

**Comment by KrauseFx** [comment]
This is a good thing: It's an external fork, so this should fail, as otherwise I could just do whatever I want with your GitHub API token :) cc @orta

**Comment by JohnSundell** [comment]
Ah, of course. That makes a ton of sense 👍 Wondering how to work around it though? "Bring your own GitHub Token"? 😄

**Comment by orta** [comment]
If your bot has no access to any repos, then it's fine to make the token public - http://danger.systems/guides/getting_started.html#setting-up-an-access-token

**Comment by KrauseFx** [comment]
Oh yah, that's right 👍

**Comment by JohnSundell** [comment]
Thanks @orta 🙏 Fixed, and retriggered the build 👍

**Comment by KrauseFx** [comment]
Oh yess, let's 🚀

**Pull request merged**
