### PR TITLE
Add observation when an actor is added to a scene.

### PR DESCRIPTION
**Pull request by z0s**
#68

### CODE REVIEW

**Comment by JohnSundell** [comment]
@z0s Looks perfect 👌 Now you need to trigger the event whenever an actor gets added to a scene, and verify that it works using a unit test 👍 (btw, you don't have to close a PR when making a change, you can simply push new commits onto your fork and the PR will automatically update) 🙂

**Comment by JohnSundell** [comment]
Hey @z0s, do you think that you'll have time to finish this one soon, or is it better if someone else takes it over? 🙂 Let me know how you want to proceed. If you need help, just ask 👍

**Comment by z0s** [comment]
@JohnSundell I have a question in regards with the add method in the Scene class. Would this be where I trigger that an actor has indeed been added?
Method add(:)

**Comment by z0s** [comment]
I would like some initial guidance in unit testing this new behavior. Should I be creating a new test method in SceneTests, or should I use an existing test? Or would I want to approach this in a different way?

**Comment by JohnSundell** [comment]
@z0s, exactly 👍 Perfect place to put it. As for a test, I think adding a test in `SceneTests` like you suggested sounds great. For inspiration on how to test events, have a look at `ActorTests`, there are several tests there that deals with events. Basically I recommend observing this new event, adding an actor to the scene, then asserting that the correct actor was passed to the event closure.

Btw, a quick GitHub tip, you don't have to paste images of code, you can use Markdown to add code directly to a comment 😃 Just wrap your code in three back-ticks (```) and it'll be formatted.

**Comment by JohnSundell** [comment]
@z0s Do you mind if I take this one over? I really need it in one of my projects 😇

**Comment by z0s** [comment]
Of course! I can learn from your solution as well!

**Comment by JohnSundell** [comment]
@z0s Cool 🙂 I made a PR with both an `actorAdded` and an `actorRemoved` event here: https://github.com/JohnSundell/ImagineEngine/pull/96. Thanks a lot for contributing and feel free to pick up any more starter tasks that will be coming up 👍

**Pull request closed without merging**
